### ISSUE TITLE
倒入课表时出现如图错误提示

### ISSUE THREAD

**Issue by Shuang-su** [0xJacky/Qi#13]
倒入课表时出现如图错误提示
![7400E0A1-D827-4AC7-B93E-58A204FE6D37](https://user-images.githubusercontent.com/103928586/187083353-b6f7a1ae-d042-4e9b-ad66-f5684120f6f3.png)

**Comment by 0xJacky** [comment]
教务系统又改了估计，明天修

**Comment by 0xJacky** [comment]
好吧 我试了一下我自己的账号是正常的，
如果可以的话发一下账号密码给 me@jackyu.cn

@Grey0520 有遇到吗？

**Comment by d3vw** [comment]
我的正常，今天下午还正常导出一次。

**Comment by 0xJacky** [comment]
不方便发账号密码的话，发教务系统下载下来的课表给我也行

**Comment by 0xJacky** [comment]
因为电子技术基础这门课没给地址，导致了错误，已修复
